name: 'Terraform destroy'

on:
  schedule:
  - cron: '0 14 * * 2'
  - cron: '0 13 * * 4'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  terraform_destroy:
    name: 'Destroy the cluster'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: run the script
      run: ./terraform.py -w gcluster -o deus -d -m "Scheduled deletion"
      env:
        TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
