name: 'Terraform'

on:
  schedule:
  - cron: '0 12 * * 2'
  - cron: '0 11 * * 4'

jobs:
  terraform:
    name: 'Create a cluster'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        ls -l
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run the script
      run: ./terraform.py -w gcluster -o deus -m "Scheduled run"
      env:
        TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
