name: 'Terraform destroy'

on:
  schedule:
  - cron: '0 14 * * 2'
  - cron: '0 13 * * 4'

jobs:
  terraform_destroy:
    name: 'Destroy a cluster'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: run the script
      run: ./terraform.py -w gcluster -o deus -d -m "Scheduled deletion"
      env:
        TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
